# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
        pod 'Alamofire'
        pod 'PromiseKit'
        pod 'MBProgressHUD'
        
        # Cache
        pod 'Kingfisher', '=4.9'
        
        pod 'RxSwift'
        
        pod 'RealmSwift'
end

target 'TikiTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TikiTest
  shared_pods

  target 'TikiTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TikiTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

